### PR TITLE
fix authentication breaks with custom adapter

### PR DESCRIPTION
**Pull request by humrochagf**

### CODE REVIEW

**Comment by clokep** [comment]
@humrochagf Can you please provide more of an explanation of what's happening and what this fixes? Maybe some minimum example code? Thanks!

**Comment by humrochagf** [comment]
this [line](https://github.com/percipient/django-allauth-2fa/blob/master/allauth_2fa/views.py#L64) at `TwoFactorAuthenticate` has a call to a super of a adapter instance. But it assumes that you are using the `OTPAdapter`.

But it isn't true when a custom adapter is set on settings.py:

```
ACCOUNT_ADAPTER = 'myapp.adapter.MyCustomAdapter'
```

**Comment by clokep** [comment]
@humrochagf I'm using a customer adapter in my project and don't have this issue. What does your customer adapter look like? Does it override the `login` method?

**Comment by humrochagf** [comment]
Yes, that is my custom adapter:

```python
class PreserveNextOTPAdapter(DefaultAccountAdapter):

    def login(self, request, user):

        # Require two-factor authentication if it has been configured.
        if user.totpdevice_set.filter(confirmed=True).all():
            request.session['allauth_2fa_user_id'] = user.id

            next = request.GET.get('next') or request.POST.get('next')

            if next:
                if type(next) is list:
                    next = next[0]

                next = '?next={}'.format(next)

            else:
                next = ''

            raise ImmediateHttpResponse(
                response=HttpResponseRedirect(
                    reverse('two-factor-authenticate') + next
                )
            )

        # Otherwise defer to the original allauth adapter.
        return super(PreserveNextOTPAdapter, self).login(request, user)
```

**Comment by clokep** [comment]
Ah, I see. It's because we're calling `super` outside of the class, which is kind of weird.

As an aside, it looks like your customer adapter is trying to fix a bug mentioned in this comment: https://github.com/percipient/django-allauth-2fa/pull/32#issuecomment-254499447 I don't think we ever filed an issue on supporting `next` appropriately, but I find it really annoying -- so if you have a good fix for that I'd love to include it!

I'll review this soon. Feel free to bug me if I don't get to it within the next week!

**Comment by humrochagf** [comment]
yeah, i not submitted a proper fix to that yet because i am working on a more generic version of this to pass  on another parameters like google analytics utm_source info

**Comment by clokep** [comment]
Cool. This seems to fix the problem!

I tested this by
* Copying you test adapter into the `test` application
* Logging in
* Turning on 2FA & Logging out
* Logging in again
* After entering the proper token, I got an exception at `allauth_2fa/views.py in form_valid, line 64`:

```
TypeError at /accounts/two-factor-authenticate

super(type, obj): obj must be an instance or subtype of type
```

Applying this branch fixed the exception.

**Comment by clokep** [comment]
Of course I did additional testing now...and this is breaking *my* custom adapter. I'll need to figure out how to fix that.

**Comment by clokep** [comment]
@humrochagf So after looking at this again, I think this is the wrong fix. If you inherit from `OTPAdapter`, everything should work fine. Can you try that and let me know if it works? I'm going to back this out for now since it's breaking code for me.

**Comment by humrochagf** [comment]
No problem, i will document all of that to help new users that need to make changes at the adapter too

**Comment by clokep** [comment]
More documentation is good! 👍 Thanks. :)

Note that this was reverted in 2ee5b8ce371b10ae3b8de970885a5c1d4e4ef6e2.

**Pull request merged**
