### PR TITLE
Add wheel target configuration to hatch build process to include templates

### LINKED ISSUE #176: Templates are not included in 0.11.0 wheel distribution
We upgraded to v.0.11.0 and started seeing some  `TemplateDoesNotExist` errors in our staging env. After some troubleshooting it seems that the html template are missing in the wheel distribution of the release. This completely breaks the package.

Version 0.10.0 manually downloaded from PyPi: 

```
$ unzip -l django_allauth_2fa-0.10.0-py3-none-any.whl 
Archive:  django_allauth_2fa-0.10.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
       23  2022-07-04 11:28   allauth_2fa/__init__.py
     1474  2022-07-04 11:28   allauth_2fa/adapter.py
      321  2022-07-04 11:28   allauth_2fa/app_settings.py
     2952  2022-07-04 11:28   allauth_2fa/forms.py
     4049  2022-07-04 11:28   allauth_2fa/middleware.py
      728  2022-07-04 11:28   allauth_2fa/mixins.py
      633  2022-07-04 11:28   allauth_2fa/urls.py
     1084  2022-07-04 11:28   allauth_2fa/utils.py
     6776  2022-07-04 11:28   allauth_2fa/views.py
      340  2022-07-04 11:28   allauth_2fa/templates/allauth_2fa/authenticate.html
      770  2022-07-04 11:28   allauth_2fa/templates/allauth_2fa/backup_tokens.html
      391  2022-07-04 11:28   allauth_2fa/templates/allauth_2fa/remove.html
      621  2022-07-04 11:28   allauth_2fa/templates/allauth_2fa/setup.html
      625  2022-07-04 11:29   django_allauth_2fa-0.10.0.dist-info/LICENSE
     4944  2022-07-04 11:29   django_allauth_2fa-0.10.0.dist-info/METADATA
       92  2022-07-04 11:29   django_allauth_2fa-0.10.0.dist-info/WHEEL
       12  2022-07-04 11:29   django_allauth_2fa-0.10.0.dist-info/top_level.txt
     1566  2022-07-04 11:29   django_allauth_2fa-0.10.0.dist-info/RECORD
---------                     -------
    27401                     18 files
```
    
Version 0.11.0 manually downloaded from PyPi: 

```
$ unzip -l django_allauth_2fa-0.11.0-py3-none-any.whl 
Archive:  django_allauth_2fa-0.11.0-py3-none-any.whl
  Length      Date    Time    Name
---------  ---------- -----   ----
       59  2020-02-02 00:00   allauth_2fa/__init__.py
     4103  2020-02-02 00:00   allauth_2fa/adapter.py
      643  2020-02-02 00:00   allauth_2fa/app_settings.py
     3305  2020-02-02 00:00   allauth_2fa/forms.py
     4354  2020-02-02 00:00   allauth_2fa/middleware.py
      882  2020-02-02 00:00   allauth_2fa/mixins.py
      594  2020-02-02 00:00   allauth_2fa/urls.py
      993  2020-02-02 00:00   allauth_2fa/utils.py
     7244  2020-02-02 00:00   allauth_2fa/views.py
     4870  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/METADATA
       87  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/WHEEL
      625  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/licenses/LICENSE
     1054  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/RECORD
---------                     -------
    28813                     13 files
```

### PR DESCRIPTION
**Pull request by valberg**
Before:

```
$ unzip -l django_allauth_2fa-0.11.0-py3-none-any.whl                                                                
Archive:  django_allauth_2fa-0.11.0-py3-none-any.whl                                                                 
  Length      Date    Time    Name                                                                                   
---------  ---------- -----   ----                     
      210  2020-02-02 00:00   manage.py                                                                              
       59  2020-02-02 00:00   allauth_2fa/__init__.py                                                                
     4103  2020-02-02 00:00   allauth_2fa/adapter.py      
     1349  2020-02-02 00:00   allauth_2fa/app_settings.py 
     3598  2020-02-02 00:00   allauth_2fa/forms.py                                                                   
     4354  2020-02-02 00:00   allauth_2fa/middleware.py                                                              
      882  2020-02-02 00:00   allauth_2fa/mixins.py                                                                  
      594  2020-02-02 00:00   allauth_2fa/urls.py                                                                    
      993  2020-02-02 00:00   allauth_2fa/utils.py                                                                   
     7244  2020-02-02 00:00   allauth_2fa/views.py        
     2807  2020-02-02 00:00   docs/conf.py                                                                           
     4895  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/METADATA
       87  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/WHEEL                                              
      625  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/licenses/LICENSE                                   
     1189  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/RECORD
---------                     -------                                                                                
    32989                     15 files    
```

After

```
This fixes #176.

$ unzip -l django_allauth_2fa-0.11.0-py3-none-any.whl    
Archive:  django_allauth_2fa-0.11.0-py3-none-any.whl                                                                 
  Length      Date    Time    Name                     
---------  ---------- -----   ----                                                                                   
       59  2020-02-02 00:00   allauth_2fa/__init__.py                                                                
     4103  2020-02-02 00:00   allauth_2fa/adapter.py                                                                 
     1349  2020-02-02 00:00   allauth_2fa/app_settings.py                                                            
     3598  2020-02-02 00:00   allauth_2fa/forms.py                                                                   
     4354  2020-02-02 00:00   allauth_2fa/middleware.py
      882  2020-02-02 00:00   allauth_2fa/mixins.py                                                                                                                                  
      594  2020-02-02 00:00   allauth_2fa/urls.py                                                                    
      993  2020-02-02 00:00   allauth_2fa/utils.py                                                                   
     7244  2020-02-02 00:00   allauth_2fa/views.py                                                                   
      340  2020-02-02 00:00   allauth_2fa/templates/allauth_2fa/authenticate.html                                    
      770  2020-02-02 00:00   allauth_2fa/templates/allauth_2fa/backup_tokens.html                                   
      431  2020-02-02 00:00   allauth_2fa/templates/allauth_2fa/remove.html                                          
      660  2020-02-02 00:00   allauth_2fa/templates/allauth_2fa/setup.html                                           
     4895  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/METADATA                                           
       87  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/WHEEL                                              
      625  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/licenses/LICENSE                                   
     1622  2020-02-02 00:00   django_allauth_2fa-0.11.0.dist-info/RECORD                                             
---------                     -------                                                                                
    32709                     17 files 
```

I'm explicitly only including files ending in .py and .html to avoid files like ruff.toml and py.typed.

The question is whether we do a hotfix of 0.11.0, or if we just release a 0.12.0 with the other additional stuff in main.

### CODE REVIEW

**Review by akx — APPROVED** [review]

**Review by akx — CHANGES_REQUESTED** [review]
We do want py.typed to be included though!

**Comment by valberg** [comment]
> We do want py.typed to be included though!

<themoreyouknow.gif>

I'll be right on it!

**Review by akx — APPROVED** [review]

**Comment by akx** [comment]
Will backport this to a v0.11.1 patch release 👍

**Comment by valberg** [comment]
@akx should we remove 0.11.0 from pypi?

**Comment by akx** [comment]
@valberg Sure, <del>I can yank it once 0.11.1 gets published.</del> yanked it!

**Pull request merged**
