### PR TITLE
Pass User model USERNAME_FIELD attribute to otpauth

### PR DESCRIPTION
**Pull request by vgaicuks**

### CODE REVIEW

**Comment by clokep** [comment]
@vgaicuks Thanks for the pull request! Could you provide a description of what this is fixing? Under what case is this an issue?

**Comment by vgaicuks** [comment]
On case when in UserModel username attribute is an e-mail or username field doesn't exist (not Django default behaviour) method "get" throw an exception "AttributeError" on otpauth_url generation. Django AbstractUser class has USERNAME_FIELD constant for getting correct username attribute name.

**Comment by clokep** [comment]
The relevant documentation around [`USERNAME_FIELD
`](https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#django.contrib.auth.models.CustomUser.USERNAME_FIELD). Is there any reason to not call [`get_username()`](https://docs.djangoproject.com/en/1.10/topics/auth/customizing/#django.contrib.auth.models.AbstractBaseUser.get_username) instead?

**Comment by vgaicuks** [comment]
Awesome! Your solution more elegant that mine.

**Comment by clokep** [comment]
Looks good! I'll do some manual testing and then merge this. 👍 Thanks.

**Comment by clokep** [comment]
Thanks again! I'll try to do a release soon!

**Pull request merged**
