### PR TITLE
Added Django 1.10 Middleware Mixin

### PR DESCRIPTION
**Pull request by MightySCollins**
To make the middleware compatible with Django 1.10 this mixin needs to be added as per https://docs.djangoproject.com/en/1.10/topics/http/middleware/#upgrading-middleware

### CODE REVIEW

**Comment by clokep** [comment]
Thanks for the PR!

@MightySCollins You'll need to catch the `ImportError` on older versions of Django to make this compatible. You should just be able to set `MiddlewareMixin` to `object` if an `ImportError` is raised.

I wonder if there's a way we should modify the settings in the Django 1.10 tests to ensure this is tested.

**Comment by MightySCollins** [comment]
@clokep Yep, I was just in the process of adding that as you did your comment :smile:. Ill push it up now.

Shows what happens when you rush into a change... 5075e59 should fix it

**Comment by MightySCollins** [comment]
There we go all fixed, with regards to testing I don't think much needs to be added. The tests ensure that the middleware is able to be created correctly in both versions of Django before and after 1.10 and as demonstrated by my old commit fail if this change fails.

**Comment by clokep** [comment]
Seems to work well...tests were failing for me initially as I didn't update `django-otp` too. 👍

**Pull request merged**
