### PR TITLE
Include new feature from issue #169 in changelog

### PR DESCRIPTION
**Pull request by jkaeske**
Here is the updated changelog @valberg :)

### CODE REVIEW

**Comment by akx** [comment]
@jkaeske Please [rebase](https://docs.github.com/en/get-started/using-git/about-git-rebase#rebasing-commits-against-a-branch) this on top of `valohai/main` so there's just one commit left :)

**Comment by valberg** [comment]
We can just squash it

**Review by valberg — APPROVED** [review]

**Comment by akx** [comment]
@valberg Technically yeah – but knowing how to rebase is also a good learning experience 😁 

(If you decide to squash-merge, please clean up the commit message (which AFAIU can't be done on GitHub Mobile)).

**Comment by valberg** [comment]
Hmm Github mobile says it would add 5 commits if squashing - so nvm me

**Comment by jkaeske** [comment]
I think that worked, maybe? 😅

**Comment by akx** [comment]
@jkaeske Yep, it did! Thanks :)

**Comment by jkaeske** [comment]
Thanks to you @akx @valberg , for your help! :)

**Pull request merged**
