### PR TITLE
Fix issue #43 of not forwarding GET parameters when 2fa is enabled

### PR DESCRIPTION
**Pull request by humrochagf**

### CODE REVIEW

**Comment by clokep** [comment]
Looks sane at first glance! I'll test this out soon. Thanks for writing a test-case. 👍

**Comment by JelteF** [comment]
Any update on this? Would be great to see this annoyance go away.

**Comment by clokep** [comment]
Sorry for being so slow on this! I'll try to get to this by the end of the week. Thanks for the reminder!

**Comment by clokep** [comment]
I tested this manually and it seems to work well! 👍

**Comment by clokep** [comment]
Thanks! I'm going to do some release note updates and a couple other minor things and do a release for this. 👍

**Pull request merged**
